version: '3.3'
services:
  front-docker:
    image: ghcr.io/artidsun/int371-frontend-prd:latest
    container_name: frontendPrd
    ports:
      - "8081:80"
    volumes:
     - nginxPrd/conf.d /etc/nginx/conf.d
networks:
    default:
      external:
        name: project-net